((handbook . "Tamer's Handbook")
 (story . "Chapter")
 (scenario . "Section")
 (reference . "References")
 (appendix . "Appendix")
 (bibliography . "Bibliography")
 (digimon . "Laboratories")
 (index . "Index"))
